// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct P2PvpnContractClientProgram;
impl sails_rs::client::Program for P2PvpnContractClientProgram {}
pub trait P2PvpnContractClient {
    type Env: sails_rs::client::GearEnv;
    fn p_2_pvpn_contract(
        &self,
    ) -> sails_rs::client::Service<p_2_pvpn_contract::P2PvpnContractImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> P2PvpnContractClient
    for sails_rs::client::Actor<P2PvpnContractClientProgram, E>
{
    type Env = E;
    fn p_2_pvpn_contract(
        &self,
    ) -> sails_rs::client::Service<p_2_pvpn_contract::P2PvpnContractImpl, Self::Env> {
        self.service(stringify!(P2PvpnContract))
    }
}
pub trait P2PvpnContractClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<P2PvpnContractClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> P2PvpnContractClientCtors
    for sails_rs::client::Deployment<P2PvpnContractClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<P2PvpnContractClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod p_2_pvpn_contract {
    use super::*;
    pub trait P2PvpnContract {
        type Env: sails_rs::client::GearEnv;
        fn do_something(&mut self) -> sails_rs::client::PendingCall<io::DoSomething, Self::Env>;
    }
    pub struct P2PvpnContractImpl;
    impl<E: sails_rs::client::GearEnv> P2PvpnContract
        for sails_rs::client::Service<P2PvpnContractImpl, E>
    {
        type Env = E;
        fn do_something(&mut self) -> sails_rs::client::PendingCall<io::DoSomething, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(DoSomething () -> String);
    }
}
